import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

export default function Terms() {
  return (
    <div className="min-h-screen bg-background">
      <header className="border-b">
        <div className="container mx-auto px-4 py-4">
          <h1 className="text-2xl font-semibold">Signify</h1>
        </div>
      </header>
      
      <main className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto">
          <Card>
            <CardHeader>
              <CardTitle className="text-3xl">Terms of Service</CardTitle>
              <p className="text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>
            </CardHeader>
            
            <CardContent className="space-y-6 prose prose-sm max-w-none">
              <section>
                <h2 className="text-xl font-semibold mb-3">1. Acceptance of Terms</h2>
                <p>
                  By accessing and using Signify, you accept and agree to be bound by the terms and 
                  provision of this agreement.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold mb-3">2. Description of Service</h2>
                <p>
                  Signify is a writing platform that captures and verifies keystroke data to provide 
                  proof of human authorship. Users can create documents, and the platform records 
                  keystroke patterns to verify authentic human writing.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold mb-3">3. User Accounts</h2>
                <ul className="list-disc pl-6 space-y-2">
                  <li>You must provide accurate and complete information when creating an account</li>
                  <li>You are responsible for maintaining the security of your account</li>
                  <li>You must not share your account credentials with others</li>
                  <li>You must notify us immediately of any unauthorized use of your account</li>
                </ul>
              </section>

              <section>
                <h2 className="text-xl font-semibold mb-3">4. Content and Data</h2>
                <ul className="list-disc pl-6 space-y-2">
                  <li>You retain ownership of all content you create on Signify</li>
                  <li>By publishing content, you grant us a license to display it publicly</li>
                  <li>Keystroke data is collected for verification purposes only</li>
                  <li>You may export your data at any time</li>
                  <li>You are responsible for the content you publish</li>
                </ul>
              </section>

              <section>
                <h2 className="text-xl font-semibold mb-3">5. Prohibited Uses</h2>
                <p>You may not use Signify to:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Publish illegal, harmful, or offensive content</li>
                  <li>Attempt to circumvent keystroke verification systems</li>
                  <li>Upload content generated by AI or other automated systems</li>
                  <li>Violate any applicable laws or regulations</li>
                  <li>Interfere with the service or other users</li>
                </ul>
              </section>

              <section>
                <h2 className="text-xl font-semibold mb-3">6. Privacy</h2>
                <p>
                  Your privacy is important to us. Please review our Privacy Policy to understand 
                  how we collect, use, and protect your information.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold mb-3">7. Termination</h2>
                <p>
                  We may terminate or suspend your account at any time for violations of these terms. 
                  You may delete your account at any time.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold mb-3">8. Limitation of Liability</h2>
                <p>
                  Signify is provided &ldquo;as is&rdquo; without warranties. We are not liable for any damages 
                  arising from your use of the service.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold mb-3">9. Changes to Terms</h2>
                <p>
                  We may update these terms at any time. Continued use of the service constitutes 
                  acceptance of any changes.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold mb-3">10. Contact</h2>
                <p>
                  If you have questions about these terms, please contact us through our support page.
                </p>
              </section>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  )
}
